# Generated by Django 5.2 on 2025-04-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_students_userame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='userame',
            new_name='username',
        ),
    ]
