# Generated by Django 5.2 on 2025-04-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_students_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Profile',
        ),
    ]
